#!/usr/bin/env bash


Ape=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

banner() { cat<<'EOF'

     _----------_,
    ,"__         _-:,   shAPE = 
   /    ""--_--""...:\   Sharing
  /         |.........\   A
 /          |..........\   Programmer
/,         _'_........./:   Enviroment
! -,    _-"   "-_... ,;;:    
\   -_-"         "-_/;;;;    timm@ieee.org
 \   \             /;;;;'   
  \   \           /;;;;     
   '.  \         /;;;'
     "-_\_______/;;'

EOF
}

trans1() { gawk '
  function transpile(s) {
    s = gensub(/\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/, 
              "[\"\\1\\2\"]","g",s) 
    for(i in Pat) gsub(i,Pat[i],s)
    return s
  }
  BEGIN                  { In=1 }
  !In && /^#define[ \t]/ { Pat["\\<" $2 "\\>"]= $3   }
  /```awk/               { In=0; print "# " $0; next }
  /```($|[^a])/          { In=1; print "# " $0; next }
  ! In                   { $0 = transpile($0) }
                         { print (In ? "# " : "")  $0 } '
}
trans() {
  local j=$Ape/.var/$(basename $1 .md).awk
  if [ "$1" -nt "$j" ]; then
    cat $1 | trans1 > $j
  fi
}
doc() {
  if [ "$Ape/README.md" -nt "$1" ]; then
    x=$(mktemp)
    cat $Ape/README.md | gawk '
        BEGIN { FS="\n"; RS="" } 
              { print; exit 0  }'  > $x
    cat $1 | gawk '
        BEGIN { FS="\n"; RS="" } 
        NR==1 && $1~/name=top>/ { next }
              { print ""; print }'  >> $x
    mv $x $1
  fi
}
here() { cd $1; basename `pwd`; }

exists() { 
  if [ ! -f "$Ape/$1"  ]; then
    if  [ -f "$Ape/$2" ]; then
      cp $Ape/$2 > $Ape/$1
    fi
  fi
}

##################################################

mkdir -p $Ape/.var
mkdir -p $Ape/etc/dot

exists .gitignore etc/dot/gitignore
exists .travis.yml etc/dot/travisyml

if ls      *.md >/dev/null 2>&1; then for i in *.md      ; do doc   $i; done fi
if ls test/*.md >/dev/null 2>&1; then for i in test/*.md ; do doc   $i; done fi
if ls src/*.md  >/dev/null 2>&1; then for i in src/*.md ;  do doc   $i; done fi

if ls test/*.md >/dev/null 2>&1; then for i in test/*.md ; do trans $i; done fi
if ls src/*.md  >/dev/null 2>&1; then for i in src/*.md ;  do trans $i; done fi

k=$Ape/.var/$(basename $1 .md).awk
if [ -f "$k" ]; then
  if [ -t 0 ]; then
    echo "AWKPATH='$Ape/.var:$AWKPATH'  gawk  -f $k"
    AWKPATH="$Ape/.var:$AWKPATH"  gawk  -f $k
  else
    cat - | AWKPATH="$Ape/.var:$AWKPATH"  gawk $j -f $k
  fi 
else
  _c0="\033[00m"     # white
  _c1="\033[01;32m"  # green
  _c2="\033[01;34m"  # blue
  _c3="\033[31m"     # red
  _c5="\033[35m"     # purple
  _c6="\033[33m"     # yellow
  _c7="\033[36m"     # turquoise 
  _c8="\033[96m"     # magenta
  bash -c "echo  -ne '\033[96m'"
  banner
  bash -c "echo  -ne '\033[00m'"
  PROMPT_COMMAND='echo -ne "${_c2}iSH:${_c6}$(git branch 2>/dev/null | grep '^*' | colrm 1 2) ";PS1="${_c1}$_c0$(here ../..)/$(here ..)/$(here .) ${_c3}\!>${_c0}\e[m "'
  alias l='ls -G'
  alias ..='cd ..'
  alias gg="git pull"
  alias gs="git status"
  alias gp="git commit -am 'saving'; git push; git status"
  alias vi="vim -u $Ape/etc/dot/vimrc "
  alias tmux="tmux -f $Ape/etc/dot/tmuxrc "
  for c in gawk git tmux vim ; do
    if [ -z "$(which $c)" ]; then
      echo "#WARNING:  missing: $c (better install it)"
    fi
  done
  vim -E -s -u "$Ape/etc/dot/vimrc" +PluginInstall +qall
fi

